CREATE TABLE INDEXEDTABLETYPE (
  ID NUMERIC(4) NOT NULL,
  NAME VARCHAR(25),
  RID UROWID,
  PRIMARY KEY (ID)
)
ORGANIZATION INDEX 
PCTTHRESHOLD 2 
STORAGE 
( INITIAL  4K 
  NEXT  2K 
  PCTINCREASE 0
  MINEXTENTS 1
  MAXEXTENTS 1 ) 
OVERFLOW 
STORAGE 
( INITIAL  4K 
  NEXT  2K 
  PCTINCREASE 0 
  MINEXTENTS 1 
  MAXEXTENTS 1
)|
INSERT INTO INDEXEDTABLETYPE (ID, NAME, RID) VALUES (1, 'mike', '*EcLiPseLiNk1')|
INSERT INTO INDEXEDTABLETYPE (ID, NAME, RID) VALUES (2, 'merrick', '*EcLiPseLiNk2')|
INSERT INTO INDEXEDTABLETYPE (ID, NAME, RID) VALUES (3, 'rick', '*EcLiPseLiNk3')|