CREATE OR REPLACE PACKAGE SIMPLEPACKAGE1 AS 
  PROCEDURE NOARGPLSQLSP;
  PROCEDURE VARCHARPLSQLSP(X IN VARCHAR);
  PROCEDURE INOUTARGSPLSQLSP(T IN VARCHAR, U OUT VARCHAR, V OUT NUMERIC);
  PROCEDURE INOUTARGPLSQLSP(T IN OUT VARCHAR);
END SIMPLEPACKAGE1;
|
CREATE OR REPLACE PACKAGE BODY SIMPLEPACKAGE1 AS
  PROCEDURE NOARGPLSQLSP AS
  BEGIN
    null;
  END NOARGPLSQLSP;
  PROCEDURE VARCHARPLSQLSP(X IN VARCHAR) AS
  BEGIN
    null;
  END VARCHARPLSQLSP;
  PROCEDURE INOUTARGSPLSQLSP(T IN VARCHAR, U OUT VARCHAR, V OUT NUMERIC) AS
  BEGIN
    U := CONCAT('barf-' , T);
    V := 55;
  END INOUTARGSPLSQLSP;
  PROCEDURE INOUTARGPLSQLSP(T IN OUT VARCHAR) AS
  BEGIN
    T := CONCAT('barf-' , T);
  END INOUTARGPLSQLSP;
END SIMPLEPACKAGE1;
|