CREATE OR REPLACE TYPE PACKAGE1_MTAB1 AS TABLE OF NUMBER
|
CREATE OR REPLACE TYPE PACKAGE1_NRECORD AS OBJECT (
  N1 VARCHAR2(10),
  N2 DECIMAL(7,2)
)
|
CREATE OR REPLACE TYPE PACKAGE1_MRECORD AS OBJECT (
  M1 PACKAGE1_MTAB1
)
|
CREATE OR REPLACE PACKAGE PACKAGE1 AS
  TYPE MTAB1 IS TABLE OF NUMBER INDEX BY BINARY_INTEGER;
  TYPE NRECORD IS RECORD (
    N1 VARCHAR2(10),
    N2 DECIMAL(7,2)
  );
  TYPE MRECORD IS RECORD (
    M1 MTAB1
  );
  PROCEDURE GETNEWREC(NEWREC OUT NRECORD);
  PROCEDURE COPYREC(ORIGINALREC IN NRECORD, NEWREC OUT NRECORD, SUFFIX IN VARCHAR2);
  PROCEDURE GETRECWITHTABLE(ORIGINALTAB IN MTAB1, NEWREC OUT MRECORD);
  FUNCTION COPYREC2(ORIGINALREC IN NRECORD, SUFFIX IN VARCHAR2) RETURN NRECORD;
  FUNCTION GETRECWITHTABLE2(ORIGINALTAB IN MTAB1) RETURN MRECORD;
END PACKAGE1;
|
CREATE OR REPLACE PACKAGE BODY PACKAGE1 AS
  PROCEDURE GETNEWREC(NEWREC OUT NRECORD) AS
  BEGIN
    NEWREC.N1 := 'new record';
    NEWREC.N2 := 100.11;
  END GETNEWREC;
  PROCEDURE COPYREC(ORIGINALREC IN NRECORD, NEWREC OUT NRECORD, SUFFIX IN VARCHAR2) AS
  BEGIN
    NEWREC.N1 := CONCAT(ORIGINALREC.N1, SUFFIX);
    NEWREC.N2 := ORIGINALREC.N2 + 0.1;
  END COPYREC;
  PROCEDURE GETRECWITHTABLE(ORIGINALTAB IN MTAB1, NEWREC OUT MRECORD) AS
  BEGIN
    NEWREC.M1 := ORIGINALTAB;
  END GETRECWITHTABLE;
  FUNCTION COPYREC2(ORIGINALREC IN NRECORD, SUFFIX IN VARCHAR2) RETURN NRECORD IS newrec NRECORD;
  BEGIN
    newrec.N1 := CONCAT(ORIGINALREC.N1, SUFFIX);
    newrec.N2 := ORIGINALREC.N2 + 0.1;
    RETURN newrec;
  END COPYREC2;     
  FUNCTION GETRECWITHTABLE2(ORIGINALTAB IN MTAB1) RETURN MRECORD IS NEWREC MRECORD;
  BEGIN
    NEWREC.M1 := ORIGINALTAB;
    RETURN NEWREC;
  END GETRECWITHTABLE2;
END PACKAGE1;
|