CREATE OR REPLACE TYPE VCARRAY AS VARRAY(4) OF VARCHAR2(20);|
CREATE OR REPLACE PROCEDURE GETVCARRAY(T IN VARCHAR, U OUT VCARRAY) AS
  BEGIN
    U := VCARRAY();
    U.EXTEND;
    U(1) := CONCAT('entry1-', T);
    U.EXTEND;
    U(2) := CONCAT('entry2-', T);
  END GETVCARRAY;
|
CREATE OR REPLACE FUNCTION GETVCARRAY2(T IN VARCHAR) RETURN VCARRAY AS
  L_DATA VCARRAY := VCARRAY();
  BEGIN
	  L_DATA.EXTEND;
	  L_DATA(1) := CONCAT('entry1-', T);
      L_DATA.EXTEND;
      L_DATA(2) := CONCAT('entry2-', T);
	  RETURN L_DATA;
  END GETVCARRAY2;
|
CREATE OR REPLACE PROCEDURE COPYVCARRAY(V IN VCARRAY, U OUT VCARRAY) AS
  BEGIN
    U := V;
    U.EXTEND;
    U(3) := 'copy';
  END COPYVCARRAY;
|
CREATE OR REPLACE FUNCTION COPYVCARRAY2(V IN VCARRAY) RETURN VCARRAY AS
  L_DATA VCARRAY := V;
  BEGIN
    L_DATA.EXTEND;
    L_DATA(3) := 'copy';
    RETURN L_DATA;
  END COPYVCARRAY2;
|
CREATE OR REPLACE PROCEDURE GETVALUEFROMVCARRAY(V IN VCARRAY, I IN INTEGER, U OUT VARCHAR2, O OUT VARCHAR2) AS
  BEGIN
      U := V(I);
      O := CONCAT('copy of ', V(I));
  END GETVALUEFROMVCARRAY;
|
CREATE OR REPLACE FUNCTION GETVALUEFROMVCARRAY2(V IN VCARRAY, I IN INTEGER) RETURN VARCHAR2 AS
  BEGIN
	  RETURN V(I);
  END GETVALUEFROMVCARRAY2;
|