CREATE OR REPLACE TYPE PHONE_TYPE AS OBJECT (
    HOME VARCHAR2(20),
    CELL VARCHAR2(20)
);
|
CREATE OR REPLACE TYPE EMP_TYPE AS OBJECT (
    ID NUMBER,
    NAME VARCHAR2(20),
    PHONE PHONE_TYPE
);
|

CREATE TABLE EMP_TYPE_TABLE OF EMP_TYPE;|
INSERT INTO EMP_TYPE_TABLE VALUES (EMP_TYPE(66, 'BUBBLES', PHONE_TYPE('(613) 234-4567', '(613) 858-3434')));|
INSERT INTO EMP_TYPE_TABLE VALUES (EMP_TYPE(69, 'RICKY', PHONE_TYPE('(613) 344-1232', '(613) 823-2323')));|
INSERT INTO EMP_TYPE_TABLE VALUES (EMP_TYPE(99, 'JULIAN', PHONE_TYPE('(613) 424-0987', '(613) 555-8888')));|

CREATE OR REPLACE PROCEDURE GET_EMP_TYPE_BY_ID(EID IN NUMBER, ETYPE OUT EMP_TYPE) AS
BEGIN
	SELECT VALUE(E) INTO ETYPE FROM EMP_TYPE_TABLE E WHERE E.ID = EID;
END GET_EMP_TYPE_BY_ID;
|

CREATE OR REPLACE FUNCTION GET_EMP_TYPE_BY_ID_2(EID IN NUMBER) RETURN EMP_TYPE AS
ETYPE EMP_TYPE;
BEGIN
    SELECT VALUE(E) INTO ETYPE FROM EMP_TYPE_TABLE E WHERE E.ID = EID;
    RETURN ETYPE;
END GET_EMP_TYPE_BY_ID_2;
|