CREATE OR REPLACE PACKAGE SIMPLEPACKAGE2 AS 
    FUNCTION FINDPLSQLMAXSAL RETURN DECIMAL;
    FUNCTION FINDPLSQLMAXSALFORDEPT(DEPT IN DECIMAL) RETURN DECIMAL;
END SIMPLEPACKAGE2;
|
CREATE OR REPLACE PACKAGE BODY SIMPLEPACKAGE2 AS
    FUNCTION FINDPLSQLMAXSAL RETURN DECIMAL AS
    MAXSAL DECIMAL(7,2);
    BEGIN
        SELECT max(SAL) INTO MAXSAL FROM SIMPLESF;
        RETURN(MAXSAL);
    END FINDPLSQLMAXSAL;
    FUNCTION FINDPLSQLMAXSALFORDEPT(DEPT IN DECIMAL) RETURN DECIMAL AS
    MAXSAL DECIMAL(7,2);
    BEGIN
        SELECT max(SAL) INTO MAXSAL FROM SIMPLESF WHERE DEPTNO = DEPT;
        RETURN(MAXSAL);
    END FINDPLSQLMAXSALFORDEPT;

END SIMPLEPACKAGE2;
|