CREATE OR REPLACE PACKAGE PACKAGE2 AS
  TYPE TAB1 IS TABLE OF VARCHAR2(111) INDEX BY BINARY_INTEGER;
  TYPE ORECORD IS RECORD (
    O1 VARCHAR2(10),
    O2 DECIMAL(7,2)
  );
  TYPE TAB2 IS TABLE OF ORECORD INDEX BY BINARY_INTEGER;
  PROCEDURE COPYTABLE(OLDTAB IN TAB1, NEWTAB OUT TAB1);
  PROCEDURE SETRECORD(INREC IN ORECORD, NEWTAB OUT TAB2);
  FUNCTION COPYTABLE2(OLDTAB IN TAB1) RETURN TAB1;
  FUNCTION SETRECORD2(INREC IN ORECORD) RETURN TAB2;
END PACKAGE2;
|
CREATE OR REPLACE PACKAGE BODY PACKAGE2 AS
  PROCEDURE COPYTABLE(OLDTAB IN TAB1, NEWTAB OUT TAB1) AS
  BEGIN
    NEWTAB := OLDTAB;
  END COPYTABLE;
  PROCEDURE SETRECORD(INREC IN ORECORD, NEWTAB OUT TAB2) AS
  BEGIN
	  NEWTAB(0) := INREC;
  END SETRECORD;
  FUNCTION COPYTABLE2(OLDTAB IN TAB1) RETURN TAB1 IS NEWTAB TAB1;
  BEGIN
    NEWTAB := OLDTAB;
    RETURN NEWTAB;
  END COPYTABLE2;     
  FUNCTION SETRECORD2(INREC IN ORECORD) RETURN TAB2 IS NEWTAB TAB2;
  BEGIN
      NEWTAB(0) := INREC;
      RETURN NEWTAB;
  END SETRECORD2;
END PACKAGE2;
|
CREATE OR REPLACE TYPE PACKAGE2_TAB1 AS TABLE OF VARCHAR2(111)
|
CREATE OR REPLACE TYPE PACKAGE2_ORECORD AS OBJECT (
  O1 VARCHAR2(10),
  O2 DECIMAL(7,2)
)
|
CREATE OR REPLACE TYPE PACKAGE2_TAB2 AS TABLE OF PACKAGE2_ORECORD
|