CREATE OR REPLACE TYPE PERSONTYPE AS OBJECT (
    NAME VARCHAR2(20),
    AGE NUMBER,
    GENDER VARCHAR2(1),
    INCARCERATED DATE
)|

CREATE OR REPLACE TYPE PERSONTYPE_TABLE AS TABLE OF PERSONTYPE|

CREATE OR REPLACE PROCEDURE GET_PERSONTYPE_TABLE(PTABLE OUT PERSONTYPE_TABLE) AS
BEGIN
    PTABLE := PERSONTYPE_TABLE();
    
    PTABLE.EXTEND;
    PTABLE(PTABLE.COUNT) := PERSONTYPE('BUBBLES', 32, 'M', '1990-11-19');

    PTABLE.EXTEND;
    PTABLE(PTABLE.COUNT) := PERSONTYPE('RICKY', 33, 'M', '1985-10-01');
    
    PTABLE.EXTEND;
    PTABLE(PTABLE.COUNT) := PERSONTYPE('JULIAN', 35, 'M', '1988-02-07');

    PTABLE.EXTEND;
    PTABLE(PTABLE.COUNT) := PERSONTYPE('SARAH', 25, 'F', '2002-05-12');

    PTABLE.EXTEND;
    PTABLE(PTABLE.COUNT) := PERSONTYPE('J-ROC', 27, 'M', '1998-12-17');
END GET_PERSONTYPE_TABLE;
|

CREATE OR REPLACE FUNCTION GET_PERSONTYPE_TABLE2 RETURN PERSONTYPE_TABLE AS
L_DATA PERSONTYPE_TABLE;
BEGIN
	GET_PERSONTYPE_TABLE(L_DATA);
    RETURN L_DATA;
END GET_PERSONTYPE_TABLE2;
|

CREATE OR REPLACE PROCEDURE ADD_PERSONTYPE_TO_TABLE(PTYPETOADD IN PERSONTYPE, OLDTABLE IN PERSONTYPE_TABLE, NEWTABLE OUT PERSONTYPE_TABLE) AS
BEGIN
    NEWTABLE := OLDTABLE;
    
    NEWTABLE.EXTEND;
    NEWTABLE(NEWTABLE.COUNT) := PTYPETOADD;
END ADD_PERSONTYPE_TO_TABLE;
|

CREATE OR REPLACE FUNCTION ADD_PERSONTYPE_TO_TABLE2(PTYPETOADD IN PERSONTYPE, OLDTABLE IN PERSONTYPE_TABLE) RETURN PERSONTYPE_TABLE AS
NEWTABLE PERSONTYPE_TABLE;
BEGIN
    ADD_PERSONTYPE_TO_TABLE(PTYPETOADD, OLDTABLE, NEWTABLE);
    RETURN NEWTABLE;
END ADD_PERSONTYPE_TO_TABLE2;
|
