DROP PROCEDURE GET_EMP_TYPE_BY_ID|
DROP FUNCTION GET_EMP_TYPE_BY_ID_2|
DROP PROCEDURE ADD_EMP_TYPE|
DROP FUNCTION ADD_EMP_TYPE2|
DROP TABLE EMP_TYPE_TABLE|
DROP TYPE EMP_TYPE|
DROP TYPE PHONE_TYPE|
