DROP PROCEDURE GETVCARRAY
|
DROP FUNCTION GETVCARRAY2
|
DROP PROCEDURE COPYVCARRAY
|
DROP FUNCTION COPYVCARRAY2
|
DROP PROCEDURE GETVALUEFROMVCARRAY
|
DROP FUNCTION GETVALUEFROMVCARRAY2
|
DROP TYPE VCARRAY
|