DROP PROCEDURE GET_PERSONTYPE_TABLE|
DROP FUNCTION GET_PERSONTYPE_TABLE2|
DROP PROCEDURE ADD_PERSONTYPE_TO_TABLE|
DROP FUNCTION ADD_PERSONTYPE_TO_TABLE2|
DROP TYPE PERSONTYPE_TABLE|
DROP TYPE PERSONTYPE|