///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[DBWSADVANCEDMETHODS]]
== Advanced Methods of Accessing DBWS Designtime API

This chapter describes advanced methods of accessing the EclipseLink
DBWS Designtime API.

This chapter includes the following sections:

* xref:{relativedir}/advanced_methods001.adoc#DBWSADVANCEDMETHODS001[Using DBWSBuilder with Ant]

//Using DBWSBuilder with Ant
include::{rootdir}/advanced_methods001.adoc[]
