///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[DBWSOVERVIEW002]]
=== Understanding the DBWS Builder File Properties

Use the `<property>` element in the DBWS Builder XML file to define the
necessary server properties, as shown in link:#CJAHEECA[Example 1-4]

[[CJAHEECA]]

*_Example 1-4 Sample DBWS Builder XML file_*

[source,oac_no_warn]
----
<?xml version="1.0" encoding="UTF-8"?>
<dbws-builder xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  <properties>
    <property name="projectName">procedure_test</property>
    <property name="logLevel">off</property>
    <property name="username">myName</property>
...
  </properties>
...
----

See xref:{relativedir}/overview003.adoc#CJAIABED[Example 1-5] and
xref:{relativedir}/overview003.adoc#CJAGDJAI[Example 1-6] for additional samples of a
DBWS Builder XML file.

link:#CJAGGEJF[Table 1-2] defines the valid `<property>` values:

[[CJAGGEJF]]

*_Table 1-2 DBWS Builder File Properties_*

|===
|*Property* |*Description*
|`projectName` a|
Name of the DBWS project.

Default = `myProject`

|`logLevel` a|
Defines the amount and detail EclipseLink writes to the log. Valid
values: `off`, `severe`, `warning`, `info` (default), `config`, `fine`,
`fine`, `finest`, and `all`.

See in "logging.level" in _Jakarta Persistence API (JPA) Extensions
Reference for EclipseLink_ for details.

|`username` |Username used to log into the database.

|`password` |Password of the `username` used to log into the database.

|`url` |Database URL.

|`driver` |Database driver.

|`platformClassname` a|
Specify the database platform. This must be a fully qualified class name
that extends `DatabasePlatform`.

Default = `org.eclipse.persistence.platform.database.OraclePlatform`

|`targetNamespace` a|
The target namespace value applied to generated types.

Default = `urn:`__`projectName`__

|`orSessionCustomizerClassName` a|
Name of the session customizer applied to the ORM session.

See in "session.customizer" in _Jakarta Persistence API (JPA) Extensions
Reference for EclipseLink_ for details.

|`oxSessionCustomizerClassName` a|
Name of the session customizer applied to the OXM session.

See in "session.customizer" in _Jakarta Persistence API (JPA) Extensions
Reference for EclipseLink_ for details.

|`dataSource` |JNDI name of the data source, as defined on the target
application server.

|`wsdlLocationURI` a|
Location URI value, set in generated WSDL.

Default = `REPLACE_WITH_ENDPOINT_ADDRESS`

|===
