/*
 * Copyright (c) 1998, 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0
 */

// Contributors:
//     Oracle - initial API and implementation from Oracle TopLink
package org.eclipse.persistence.internal.sessions.coordination.corba.sun;


/**
* org/eclipse/persistence/internal/remotecommand/corba/sun/CommandDataHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from rcm.idl
* Tuesday, March 30, 2004 2:00:14 PM EST
*/
public final class CommandDataHolder implements org.omg.CORBA.portable.Streamable {
    public byte[] value;

    public CommandDataHolder() {
    }

    public CommandDataHolder(byte[] initialValue) {
        value = initialValue;
    }

    @Override
    public void _read(org.omg.CORBA.portable.InputStream i) {
        value = org.eclipse.persistence.internal.sessions.coordination.corba.sun.CommandDataHelper.read(i);
    }

    @Override
    public void _write(org.omg.CORBA.portable.OutputStream o) {
        org.eclipse.persistence.internal.sessions.coordination.corba.sun.CommandDataHelper.write(o, value);
    }

    @Override
    public org.omg.CORBA.TypeCode _type() {
        return org.eclipse.persistence.internal.sessions.coordination.corba.sun.CommandDataHelper.type();
    }
}
