path_classifiers:

  # exclude tests
  test:
  - "**/src/test"
  - "**/src/it"
  - "**/*.test"
  - "**/tests"
  - "performance"

  # exclude docs
  docs:
  - "about.html"
  - "license.html"
  - "readme.html"

extraction:
  java:
    index:
      java_version: 11
      maven:
        version: 3.6.3
      build_command: "mvn -DskipTests -Denforcer.skip clean package"

