#
# Copyright (c) 2021 Contributors to the Eclipse Foundation
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

path_classifiers:

  # exclude tests
  test:
    - "**/src/test"
    - "**/src/it"
    - "**/*.test"
    - "**/tests"
    - "performance"

  # exclude docs
  docs:
    - "about.html"
    - "license.html"
    - "readme.html"
    - "project-admin"

extraction:
  java:
    index:
      java_version: 11
      maven:
        version: 3.8.1
      build_command: "mvn -DskipTests -Denforcer.skip clean package"
