/*
 * Copyright (c) 2026 Contributors to the Eclipse Foundation. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0,
 * or the Eclipse Distribution License v. 1.0 which is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
 */

package org.eclipse.persistence.jpa.test.uuid;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import java.util.UUID;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;

import org.eclipse.persistence.internal.jpa.EntityManagerFactoryImpl;
import org.eclipse.persistence.jpa.test.framework.DDLGen;
import org.eclipse.persistence.jpa.test.framework.Emf;
import org.eclipse.persistence.jpa.test.framework.EmfRunner;
import org.eclipse.persistence.jpa.test.framework.Property;
import org.eclipse.persistence.jpa.test.uuid.model.UUIDNullBindingEntity;
import org.junit.Assume;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;

/**
 * Regression tests for issue #2717: binding null UUIDs to an existing PostgreSQL schema.
 */
@RunWith(EmfRunner.class)
public class TestUUIDNullBinding {

    @Emf(name = "TestUUIDNullBinding", createTables = DDLGen.NONE,
            classes = {UUIDNullBindingEntity.class},
            properties = {
                    @Property(name = "eclipselink.ddl-generation", value = "none"),
                    @Property(name = "eclipselink.jdbc.bind-parameters", value = "true")
            })
    private EntityManagerFactory emf;

    @Before
    public void createSchema() {
        Assume.assumeTrue("Test requires PostgreSQL native UUID columns",
                ((EntityManagerFactoryImpl) emf).getDatabaseSession().getPlatform().isPostgreSQL());

        // Create the table independently, as in the issue's reproducer.
        EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            em.createNativeQuery("DROP TABLE IF EXISTS UUID_NULL_BINDING").executeUpdate();
            em.createNativeQuery("CREATE TABLE UUID_NULL_BINDING ("
                    + "ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, OPTIONAL_UUID UUID)").executeUpdate();
            em.getTransaction().commit();
            emf.getCache().evictAll();
        } finally {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            em.close();
        }
    }

    @Test
    public void testPersistAndUpdateUUID() {
        UUIDNullBindingEntity entity = new UUIDNullBindingEntity();
        EntityManager em = emf.createEntityManager();
        try {
            em.getTransaction().begin();
            // Leave the UUID unset, as in issue #2717, and force the INSERT to execute.
            em.persist(entity);
            em.flush();
            assertNotNull(entity.getId());

            // Flush each change so both non-null and null UPDATE parameters reach PostgreSQL.
            // Do not read the entity yet: a read caches the JDBC type from result-set metadata
            // and would hide the incorrect type inference when binding a null UUID.
            UUID uuid = UUID.randomUUID();
            entity.setOptionalUuid(uuid);
            em.flush();
            assertEquals(1L, ((Number) em.createNativeQuery("SELECT COUNT(*) FROM UUID_NULL_BINDING "
                    + "WHERE ID = ? AND OPTIONAL_UUID = ?")
                    .setParameter(1, entity.getId()).setParameter(2, uuid).getSingleResult()).longValue());
            entity.setOptionalUuid(null);
            em.flush();
            em.getTransaction().commit();
        } finally {
            if (em.getTransaction().isActive()) {
                em.getTransaction().rollback();
            }
            em.close();
        }

        emf.getCache().evictAll();
        em = emf.createEntityManager();
        try {
            UUIDNullBindingEntity stored = em.find(UUIDNullBindingEntity.class, entity.getId());
            assertNotNull(stored);
            assertNull(stored.getOptionalUuid());
        } finally {
            em.close();
        }
    }
}
