///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

:description: EclipseLink
:keywords: eclipselink, java, jpa, persistence, concepts, orm, mapping

== Understanding the Persistence Unit

This chapter describes details about the persistence unit and the
persistence layer.

This chapter includes the following sections:

* link:#APPDEV001[About the Persistence Unit]
* link:#APPDEV002[Building and Using the Persistence Layer]
* link:#APPDEV003[About Persisting Objects]
* link:#APPDEV004[Migrating Applications to the EclipseLink Persistence Manager]
* link:#APPDEV005[About Weaving]

//About the Persistence Unit
include::{rootdir}/app_dev001.adoc[]

//Building and Using the Persistence Layer
include::{rootdir}/app_dev002.adoc[]

//About Persisting Objects
include::{rootdir}/app_dev003.adoc[]

//Migrating Applications to the EclipseLink Persistence Manager
include::{rootdir}/app_dev004.adoc[]

//About Weaving
include::{rootdir}/app_dev005.adoc[]
