///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

:description: EclipseLink
:keywords: eclipselink, java, jpa, persistence, concepts, application server

== Database and Application Server Support

This appendix describes the database platforms and application servers
supported by EclipseLink.

This appendix includes the following sections:

* link:#APP_TL_EXT001[Database Support]
* link:#APP_TL_EXT002[Application Server Support]
* link:#APP_TL_EXT003[Non-SQL Standard Database Support: NoSQL]

//Database Support
include::{rootdir}/app_tl_ext001.adoc[]

//Application Server Support
include::{rootdir}/app_tl_ext002.adoc[]

//Non-SQL Standard Database Support: NoSQL
include::{rootdir}/app_tl_ext003.adoc[]
