///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[CACHE011]]
=== Clustering and Cache Consistency

EclipseLink applications that are deployed to an application server
cluster benefit from cluster scalability, load balancing, and failover.
These capabilities ensure that EclipseLink applications are highly
available and scale as application demand increases. EclipseLink
applications are deployed the same way in application server clusters as
they are in standalone server environments. However, additional planning
and configuration is required to ensure cache consistency in an
application server cluster.

To ensure cache consistency you perform tasks such as disabling entity
caching, refreshing the cache, setting entity expiration, and setting
optimistic locking on the cache. For more information on these topics,
see "Task 1: Configure Cache Consistency" in _Solutions Guide for
EclipseLink_.
