///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[DATA_ACCESS007]]
=== About Data Partitioning Policies

Data partitioning allows an application to scale its data across more
than a single database machine. For more information on data
partitioning, see "Using Data Partitioning to Scale Data" in _Solutions
Guide for EclipseLink_.

Some databases support clustering the database across multiple machines.
Oracle RAC allows for a single database to span multiple different
server nodes. Oracle RAC also supports table and node partitioning of
data. A database cluster allows for any of the data to be accessed from
any node in the cluster. However, it is generally more efficient to
partition the data access to specific nodes, to reduce cross node
communication. For more information, see "Clustered Databases and Oracle
RAC" in _Solutions Guide for EclipseLink_.
