///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ENTITIES005]]
=== Entities and Embedded Objects

You can use the `@Embeddable` annotation to map an embedded class. An
embeddable is a special type of class that is not directly persistent,
but persisted only with its parent entity. An embeddable can be
referenced from an entity or another embeddable using the `@Embedded`
annotation for a single reference, `@EmbeddedId` for an embedded id, or
the `@ElementCollection` annotation for a `Collection` or `Map`
reference. An embeddable can also be used in any `Map` key using the
`@MapKeyClass` annotation.

* `@Embeddable`
* `@EmbeddedId`
* `@Embedded`
* `@ElementCollection`
