///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ENTITIES001]]
=== Identifying Entities

Use the `@Entity` annotation to specify that a class is an entity.

NOTE: The entity class must also be listed in your `persistence.xml` file,
unless you set the tag `<exclude-unlisted-classes>` to false.

For more information, see Chapter 2 "Entities" in the JPA Specification.

`http://jcp.org/en/jsr/detail?id=338`
