///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[NOSQL006]]
=== About Transactions and the NoSQL Platform

The JPA transaction API is supported with NoSQL data-sources. Some NoSQL
data-sources might not support transactions, so the level of transaction
support is dependent on the NoSQL platform. JTA persistence units and
transactions are also supported, but unless the NoSQL adapter is
integrated with JTA, no XA or transaction support will be available.

If the NoSQL data-source does not support transactions, then any
database change such as `flush()` will be committed directly to the
database, and `rollback()` will not have any affect. A commit operation
that fails will not roll back any successful changes written before the
error. JPA normally does not write to the database until commit or
`flush()` are called, so there will still be some level of transaction
support offered by the persistence context.

JPA operations `persist()`, `merge()`, and `remove()` are supported.

* MongoDB—Transactions are not supported.
* Oracle NoSQL—Transactions are not supported.
