///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

== Preface

EclipseLink delivers a proven standards based enterprise Java solution
for all of your relational, XML, and JSON persistence needs based on
high performance and scalability, developer productivity, and
flexibility in architecture and design.

[[OTLCG102]][[sthref2]]

=== Audience

This document is intended for application developers and administrators
who want to know more about the concepts behind EclipseLink and its
features.

[[OTLCG105]][[sthref3]]

=== Related Documents

For more information, see the following documents in the EclipseLink
documentation set:

* _Solutions Guide for EclipseLink_
* _Jakarta Persistence API (JPA) Extensions Reference for EclipseLink_
* _Developing JAXB Applications EclipseLink MOXy_
* _Developing Persistence Architectures Using EclipseLink Database Web Services Developer's Guide_
* Java API Reference for EclipseLink
* Java Persistence specification for complete information about JPA
+
`http://jcp.org/en/jsr/detail?id=338`

[[OTLCG106]][[sthref4]]

=== Conventions

The following text conventions are used in this document:

|=======================================================================
|*Convention* |*Meaning*
|*boldface* |Boldface type indicates graphical user interface elements
associated with an action, or terms defined in text or the glossary.

|_italic_ |Italic type indicates book titles, emphasis, or placeholder
variables for which you supply particular values.

|`monospace` |Monospace type indicates commands within a paragraph,
URLs, code in examples, text that appears on the screen, or text that
you enter.
|=======================================================================
