DROP TABLE XR_VEE_ARRAY_EMP|
DROP TYPE XR_VEE_ARRAY_PHONES|
DROP TYPE XR_VEE_ARRAY_PHONE|
DROP PROCEDURE GET_VEE_ARRAY_EMP|
DROP PROCEDURE GET_VEE_ARRAY_EMPS|
DROP PROCEDURE UPDATE_VEE_ARRAY_PHS|