///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[EXTENSIBLE]]
== Making JPA Entities and JAXB Beans Extensible

This chapter provides instructions for making JPA entities and JAXB
beans extensible. Mappings can be added or modified externally, without
modifying the entity or bean source file and without redeploying the
persistence unit. This feature is useful in a Software-as-a-Service
environment where multiple clients can share applications and
datasources. It is also useful for customizing an application during
installation rather than during development.

This chapter includes the following sections:

* xref:{relativedir}/extensible001.adoc#EXTENSIBLE001[Making JPA Entities Extensible]
* xref:{relativedir}/extensible002.adoc#EXTENSIBLE002[Making JAXB Beans Extensible]
* xref:{relativedir}/extensible003.adoc#EXTENSIBLE003[Additional Resources]

*Use Case*

Users want to establish a SaaS environment, where applications and
datasources are shared by multiple clients.

*Solution*

Use the EclipseLink extensibility feature to extend JPA entities and
JAXB beans by using external mappings.

*Components*

* EclipseLink 2.4 or later.

//Making JPA Entities Extensible
include::{rootdir}/extensible001.adoc[]

//Making JAXB Beans Extensible
include::{rootdir}/extensible002.adoc[]

//Additional Resources
include::{rootdir}/extensible003.adoc[]
