///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[INSTALL]]
== Installing EclipseLink

This chapter tells how to install EclipseLink.

EclipseLink is available in several distributions which are installed in
a variety of ways, as described in the following sections:

* xref:{relativedir}/install001.adoc#INSTALL001[Prerequisites]
* xref:{relativedir}/install002.adoc#INSTALL002[Installing EclipseLink for Java SE and Jakarta EE Development]
* xref:{relativedir}/install003.adoc#INSTALL003[Installing EclipseLink NoSQL Support]
* xref:{relativedir}/install004.adoc#INSTALL004[Installing EclipseLink with OSGi Support]

//Prerequisites
include::{rootdir}/install001.adoc[]

//Installing EclipseLink for Java SE and Jakarta EE Development
include::{rootdir}/install002.adoc[]

//Installing EclipseLink NoSQL Support
include::{rootdir}/install003.adoc[]

//Installing EclipseLink with OSGi Support
include::{rootdir}/install004.adoc[]
