///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[CHDGIDEA]]
== Introduction

EclipseLink is a powerful and flexible Java persistence framework for
storing Java objects in a data store, such as a relational database or a
NoSQL database, and for converting Java objects to XML or JSON
documents. EclipseLink provides APIs and a run-time environment for
implementing the persistence layer of Java Platform, Standard Edition
(Java SE platform), and Java Platform, Enterprise Edition (Jakarta EE
platform) applications.

EclipseLink implements Jakarta Persistence API (JPA), Java Architecture
for XML Binding (JAXB), and other standards-based persistence
technologies and also includes extensions beyond those standards. For
more information about the EclipseLink project, see "Eclipse Persistence
Services Project (EclipseLink) home" at
`http://www.eclipse.org/eclipselink/`. For the EclipseLink
Documentation, Center see
`http://www.eclipse.org/eclipselink/documentation/`.

//About This Guide
include::{rootdir}/intro001.adoc[]

//What You Need to Know First
include::{rootdir}/intro002.adoc[]

//The Use Cases
include::{rootdir}/sect1test.adoc[]
