///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

=== About This Guide

This guide, _Solutions Guide for EclipseLink_, documents a number of
scenarios, or use cases, that illustrate EclipseLink features and
typical EclipseLink development processes. These are not tutorials that
lead you step-by-step through every task required to complete a project.
Rather, they document general processes and key details for solving
particular problems and then provide links to other documentation for
more information.
