///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ELJBOSS001]]
=== Introduction to the Solution

JBoss Application Server implements the Java Platform, Enterprise
Edition (Jakarta EE). JBoss 7 fully supports Jakarta EE 6, while JBoss 6
officially supports only the Jakarta EE 6 Web Profile.

By configuring JBoss to support EclipseLink, you can take advantage of
EclipseLink's full support for Jakarta Persistence API (JPA), Java
Architecture for XML Binding (JAXB), including EclipseLink's extensions
to those technologies, as well as EclipseLink Database Web Services
(DBWS) to access to relational database artifacts via a Web service.
