///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[JSON]]
== Converting Objects to and from JSON Documents

This chapter describes how EclipseLink MOXy supports the ability to
convert objects to and from JSON (JavaScript Object Notation). This
feature is useful when creating RESTful services; JAX-RS services can
accept both XML and JSON messages.

This chapter includes the following sections:

* xref:{relativedir}/json001.adoc#JSON001[Introduction to the Solution]
* xref:{relativedir}/json002.adoc#JSON002[Implementing the Solution]
* xref:{relativedir}/json003.adoc#JSON003[Additional Resources]

*Use Case*

Users need to convert objects to and from JSON documents.

*Solution*

EclipseLink provides JSON support through the EclipseLink MOXy
implementation.

*Components*

* EclipseLink 2.4 or later.
* JSON documents.

*Sample*

See the following EclipseLink samples for related information:

* `http://wiki.eclipse.org/EclipseLink/Examples/MOXy`
* `http://wiki.eclipse.org/EclipseLink/Examples/MOXy/JSON_Metadata`
* `http://wiki.eclipse.org/EclipseLink/Examples/MOXy/MOXy_JSON_Provider`

//Introduction to the Solution
include::{rootdir}/json001.adoc[]

//Implementing the Solution
include::{rootdir}/json002.adoc[]

//Additional Resources
include::{rootdir}/json003.adoc[]
