///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[JSON001]]
=== Introduction to the Solution

EclipseLink supports all MOXy object-to-XML options when reading and
writing JSON, including:

* EclipseLink's advanced and extended mapping features (in addition to
the JAXB specification)
* Storing mappings in external bindings files
* Creating dynamic models with Dynamic JAXB
* Building extensible models that support multitenant applications
