///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[MIGRATEHIBERNATE]]
== Migrating from Hibernate to EclipseLink

This chapter describes how to migrate applications from using Hibernate
JPA annotations and its native and proprietary API to using
EclipseLink's JPA implementation, provided by EclipseLink. The migration
involves converting Hibernate annotations to EclipseLink annotations,
and converting native Hibernate API to EclipseLink JPA in the
application code. Standard JPA annotations and API are left unchanged.

This chapter describes how to migrate applications from using Hibernate
JPA annotations and its native and proprietary API to using EclipseLink
JPA. The migration involves converting Hibernate annotations to
EclipseLink annotations, and converting native Hibernate API to
EclipseLink JPA in the application code. Standard JPA annotations and
API are left unchanged.

This chapter includes the following sections:

* xref:{relativedir}/migrhib001.adoc#MIGRATEHIBERNATE001[Introduction to the Solution]
* xref:{relativedir}/migrhib002.adoc#MIGRATEHIBERNATE002[Main Tasks]
* xref:{relativedir}/migrhib003.adoc#MIGRATEHIBERNATE003[Additional Resources]

*Use Case*

A developer wants to migrate applications using Hibernate as the
persistence provider to use EclipseLink instead.

*Solution*

Follow the instructions in this chapter to upgrade the application.

*Components*

* EclipseLink 2.4 or later.

//Introduction to the Solution
include::{rootdir}/migrhib001.adoc[]

//Main Tasks
include::{rootdir}/migrhib002.adoc[]

//Additional Resources
include::{rootdir}/migrhib003.adoc[]
