///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[QCN003]]
=== Limitations on the Solution

EclipseLink Database Change Notification has the following limitations:

* Changes to an object's secondary tables will not trigger it to be
invalidate unless a `@Version` annotation is used and updated in the
primary table.
* Changes to an object's `OneToMany`, `ManyToMany`, and
`ElementCollection` relationships will not trigger it to be invalidate,
unless an `@Version` annotation is used and updated in the primary
table.
