///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[SAAS001]]
=== Introduction to the Solution

With EclipseLink, you can manage persistence in cloud-enabled
applications and services. EclipseLink provides flexible SaaS solutions
that address multi-tenancy and extensibility while still maintaining
high performance and scalability, making the persistence layer of these
applications a critical component.

These features are discussed in the following chapters:

* xref:{relativedir}/extensible.adoc#EXTENSIBLE[Chapter 12, "Making JPA Entities and JAXB Beans Extensible"]
* xref:{relativedir}/metadatasource.adoc#METADATASOURCE[Chapter 13, "Using an External MetaData Source"]
* xref:{relativedir}/multitenancy.adoc#MULTITENANCY[Chapter 14, "Tenant Isolation Using EclipseLink"]
