///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[SAAS]]
== Providing Software as a Service

This chapter introduces EclipseLink features available for developing
shared applications that run in Software-as-a-Service (SaaS)
environments.

*Use Case*

Users want to establish an SaaS environment, where applications and data
are shared by multiple clients.

*Solution*

Use EclipseLink SaaS features, such as extensibility, client isolation,
and external metadata sources.

*Components*

* EclipseLink 2.4 or later.

//Introduction to the Solution
include::{rootdir}/saas001.adoc[]
