///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ELGS003]]
=== Additional Resources

See the following resources for more information about the technologies
and tools used to implement the solutions in this chapter:

* Oracle GlassFish Server Administration Guide
+
`http://docs.oracle.com/cd/E26576_01/doc.312/e24928/toc.htm`
* Oracle GlassFish Server Application Deployment Guide
+
`http://docs.oracle.com/cd/E26576_01/doc.312/e24929/toc.htm`
* Oracle GlassFish Server Application Development Guide
+
`http://docs.oracle.com/cd/E26576_01/doc.312/e24930/toc.htm`
* Oracle GlassFish Server 3.1.2 to 3.1.2.2 Documentation Library
+
`http://docs.oracle.com/cd/E26576_01/index.htm`
