CREATE TABLE IF NOT EXISTS simpletable (
  ID NUMERIC NOT NULL,
  NAME VARCHAR(25),	
  SINCE DATE, 
  PRIMARY KEY (ID) 
)|
INSERT INTO simpletable (ID, NAME, SINCE) VALUES (1, 'mike', '2001-12-25')|
INSERT INTO simpletable (ID, NAME, SINCE) VALUES (2, null,'2001-12-25')|
INSERT INTO simpletable (ID, NAME, SINCE) VALUES (3, 'rick',NULL)|