///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[PERFORMANCE]]
== Enhancing Performance

This chapter describes EclipseLink performance features, provided by
EclipseLink, and how to monitor and optimize EclipseLink-enabled
applications.

This chapter includes the following sections:

* xref:{relativedir}/performance001.adoc#PERFORMANCE001[Performance Features]
* xref:{relativedir}/performance002.adoc#PERFORMANCE002[Monitoring and Optimizing EclipseLink-Enabled Applications]

*Use Case*

Users want to improve the performance of their EclipseLink-enabled
application.

*Solution*

EclipseLink provides many configuration options that can improve
performance, such as caching. In addition, there are ways to improve the
performance of specific functions, such as using Join Fetching for
queries.

*Components*

* EclipseLink 2.4 or later.

*Sample*

See the following EclipseLink samples for related information:

* `http://wiki.eclipse.org/EclipseLink/Performance`
* `http://wiki.eclipse.org/EclipseLink/Examples/JPA/Performance`
* `http://wiki.eclipse.org/EclipseLink/Examples/JPA/Monitoring`

//Performance Features
include::{rootdir}/performance001.adoc[]

//Monitoring and Optimizing EclipseLink-Enabled Applications
include::{rootdir}/performance002.adoc[]
