///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[SCALING003]]
=== Additional Resources

See the following resources for more information about the technologies
and tools used to implement the solutions in this chapter:

The following code sample and JavaDoc resources are available:

* Code Samples
** `http://wiki.eclipse.org/EclipseLink/Examples/JPA/CacheCoordination`
** `http://wiki.eclipse.org/EclipseLink/Examples/JPA/Caching`
* See the following APIs in _Java API Reference for EclipseLink_.
** `org.eclipse.persistence.annotations.OptimisticLocking`
** `org.eclipse.persistence.annotations.Cache`
** `org.eclipse.persistence.annotations.Partitioned`
** `org.eclipse.persistence.descriptors.ClassDescriptor`
** `org.eclipse.persistence.sessions.coordination`
