///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[TESTINGJPA]]
== Testing JPA Outside a Container

This chapter describes how, with EclipseLink, you can use the
persistence unit JAR file to test your application outside the container
(for instance, in applications for the Java Platform, Standard Edition
(Java SE platform)).

This chapter includes the following sections:

* xref:{relativedir}/testingjpa001.adoc#TESTINGJPA001[Understanding JPA Deployment]
* xref:{relativedir}/testingjpa002.adoc#TESTINGJPA002[Configuring the persistence.xml File]
* xref:{relativedir}/testingjpa003.adoc#TESTINGJPA003[Using a Property Map]
* xref:{relativedir}/testingjpa004.adoc#TESTINGJPA004[Using Weaving]
* xref:{relativedir}/testingjpa005.adoc#TESTINGJPA005[Additional Resources]

*Use Case*

Users need to use EclipseLink both inside and outside the container
(such as applications for the Java SE platform).

*Solution*

This solution highlights the primary differences when using EclipseLink
outside a container.

*Components*

* EclipseLink 2.4 or later.
* An application server (such as Oracle WebLogic Server, IBM WebSphere,
or Glassfish)

//Understanding JPA Deployment
include::{rootdir}/testingjpa001.adoc[]

//Configuring the persistence.xml File
include::{rootdir}/testingjpa002.adoc[]

//Using a Property Map
include::{rootdir}/testingjpa003.adoc[]

//Using Weaving
include::{rootdir}/testingjpa004.adoc[]

//Additional Resources
include::{rootdir}/testingjpa005.adoc[]
