///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[TESTINGJPA004]]
=== Using Weaving

Weaving is a technique of manipulating the byte-code of compiled Java
classes.

EclipseLink uses weaving to enhance Plain Old Java Object (POJO) classes
and JPA entities with many features such lazy loading, change tracking,
fetch groups, and internal optimizations.

==== How to Disable or Enable Weaving in a Java SE Environment

In a Java SE environment weaving is not enabled by default. This can
affect LAZY One-To-One, Many-To-One and Basic relationships. It also has
a major effect on performance and disable attribute change tracking.

To enable weaving in Java SE, the EclipseLink agent must be used when
starting the Java VM.

[source,oac_no_warn]
----
java -javaagent:eclipselink.jar
----

Spring could also be used to allow JPA weaving in Java SE. See
`http://wiki.eclipse.org/EclipseLink/Examples/JPA/JPASpring` for more
information.

Static weaving can also be used, by including the following persistence
property,

[source,oac_no_warn]
----
<property name="eclipselink.weaving" value="static"/>
----

See "weaving" in _Jakarta Persistence API (JPA) Extensions Reference for
EclipseLink_ for more information.

==== How to Disable or Enable Weaving in a Jakarta EE Environment

In a Jakarta EE environment weaving is enabled by default (on any
Jakarta EE 5 or greater fully compliant application server, such as
Weblogic, Webspehere, and Glassfish. JBoss does not allow weaving so you
must use static weaving or Spring).

To disable weaving the weaving persistence unit property can be used,

[source,oac_no_warn]
----
<property name="eclipselink.weaving" value="false">
 
----

For more information on weaving see "weaving" in _Jakarta Persistence
API (JPA) Extensions Reference for EclipseLink_.
