///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ELGS]]
== Using EclipseLink with GlassFish Server

This chapter describes how to use EclipseLink as the persistence
provider for applications deployed to Oracle GlassFish Server.

This chapter includes the following sections:

* xref:{relativedir}/tlandgs001.adoc#ELGS001[Introduction to the Solution]
* xref:{relativedir}/tlandgs002.adoc#ELGS002[Implementing the Solution]
* xref:{relativedir}/tlandgs003.adoc#ELGS003[Additional Resources]

*Use Case*

Users want to run applications that employ JPA on Oracle GlassFish
Server.

*Solution*

The Oracle GlassFish platform provides full support for EclipseLink.
Developers writing applications for the GlassFish Server platform can
achieve full Java-to-data source integration that complies with the
Jakarta Persistence API (JPA) 2.0 specification. EclipseLink allows you
to integrate Java applications with any data source, without
compromising ideal application design or data integrity.

*Components*

* GlassFish Server 3.1.2.
* EclipseLink 2.3.0 or later.
* Any compliant JDBC database including Oracle Database, Oracle Database
Express Edition, MySQL, and so on.
* While it is not required, you may want to use a Jakarta EE integrated
development environment (IDE) for convenience during development.

//Introduction to the Solution
include::{rootdir}/tlandgs001.adoc[]

//Implementing the Solution
include::{rootdir}/tlandgs002.adoc[]

//Additional Resources
include::{rootdir}/tlandgs003.adoc[]
