///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[USINGMULTIDBS003]]
=== Additional Resources

See the following resources for more information about the technologies
and tools used to implement the solutions in this chapter:

For the following additional information about composite persistence
units, see "`@CompositeMember`," "`composite.unit`," and
"`composite-unit.member`" in _Jakarta Persistence API (JPA) Extensions
Reference for EclipseLink_:

* Limitations of composite persistence units.
* Configuring composite member persistence units that contain
dependencies.
* All persistence unit properties used by composite persistence units
and composite member persistence units
* How to pass persistence unit properties to composite member
persistence units with the `Persistence.createEntityManagerFactory`
method, while creating a composite persistence unit
`EntityManagerFactory`
* All entity manager properties used by composite persistence unit and
composite member persistence units
* How to pass entity manager properties to composite member persistence
units with the `emf.createEntityManager` method for the composite
persistence unit `EntityManagerFactory`

==== Related Javadoc

For more information, see the following APIs in _Java API Reference for
EclipseLink_:

* `PersistenceUnitProperties` class
* `Persistence.createEntityManger` class
* `EntityManagerFactory` interface
