DROP PROCEDURE TESTECHO|
DROP PACKAGE SOMEPACKAGE|
DROP FUNCTION SF_TBL1|
DROP FUNCTION BUILDTBL2|
DROP FUNCTION BUILDTBL5|
DROP FUNCTION BUILDARECORD|
DROP FUNCTION BUILDTBL4|
DROP FUNCTION BUILDCRECORD|
DROP TYPE SOMEPACKAGE_TBL5 FORCE|
DROP TYPE SOMEPACKAGE_CRECORD FORCE|
DROP TYPE SOMEPACKAGE_TBL4 FORCE|
DROP TYPE SOMEPACKAGE_TBL3 FORCE|
DROP TYPE SOMEPACKAGE_ARECORD FORCE|
DROP TYPE SOMEPACKAGE_TBL2 FORCE|
DROP TYPE SOMEPACKAGE_TBL1 FORCE|
DROP PACKAGE ADVANCED_OBJECT_DEMO|
DROP PACKAGE ANOTHER_ADVANCED_DEMO|
DROP TYPE EMP_INFO_ARRAY FORCE|
DROP TYPE EMP_INFO FORCE|
DROP TYPE EMP_OBJECT FORCE|
DROP TYPE EMP_ADDRESS FORCE|
DROP TYPE REGION FORCE|
DROP PROCEDURE BOOL_IN_TEST|
DROP PACKAGE BODY TEST_TYPES|
DROP PACKAGE TEST_TYPES|
DROP PACKAGE BODY LTBL_PKG|
DROP PACKAGE LTBL_PKG|
DROP TYPE LTBL_PKG_LTBL_TAB|
DROP TYPE LTBL_PKG_LTBL_REC|
DROP TABLE LTBL|
DROP PACKAGE BODY TESMANPACK|
DROP PACKAGE TESMANPACK|
DROP TABLE TESMAN_TABLE1|
DROP TABLE TESMAN_TABLE2|
DROP TABLE TESMAN_TABLE3| 
DROP TYPE TESMAN_TYPE3|
DROP TYPE TESMAN_TYPE2|
DROP TYPE TESMAN_TYPE1|