/*******************************************************************************
 * Copyright (c) 1998, 2010 Oracle. All rights reserved.
 * This program and the accompanying materials are made available under the 
 * terms of the Eclipse Public License v1.0 and Eclipse Distribution License v. 1.0 
 * which accompanies this distribution. 
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at 
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *     Oracle - initial API and implementation from Oracle TopLink
******************************************************************************/
package org.eclipse.persistence.tools.workbench.mappingsplugin.ui.common.cell;

import javax.swing.Icon;

import org.eclipse.persistence.tools.workbench.framework.resources.ResourceRepository;
import org.eclipse.persistence.tools.workbench.framework.uitools.NoneSelectedCellRendererAdapter;
import org.eclipse.persistence.tools.workbench.mappingsmodel.MWQueryKey;



public class QueryKeyCellRendererAdapter extends NoneSelectedCellRendererAdapter {

	public QueryKeyCellRendererAdapter(ResourceRepository repository) {
		super(repository);
	}

	protected String buildNonNullValueText(Object value) {
		return ((MWQueryKey) value).getName();
	}
	
    protected Icon buildNonNullValueIcon(Object value) {
    	MWQueryKey qk = (MWQueryKey) value;
		return this.resourceRepository().getIcon(qk.isAutoGenerated() ? "queryKey" : "queryKey.userDefined");
	}

}
