///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[DATA_ACCESS005]]
=== About Connections

A connection is an object that provides access to a data source by way
of the driver you configure your application to use. Relational projects
use JDBC to connect to the data source; EIS projects use JCA.
EclipseLink uses the interface
`org.eclipse.persistence.internal.databaseaccess.Accessor` to wrap data
source connections. This interface is accessible from certain events.

Typically, when using a server session, EclipseLink uses a different
connection for both reading and writing. This lets you use
nontransactional connections for reading and avoid maintaining
connections when not required.

By default, an EclipseLink server session acquires connections lazily:
that is, only during the commit operation of a persistence unit.
Alternatively, you can configure EclipseLink to acquire a write
connections at the time you acquire a client sessions.

Connections can be allocated from internal or external connection pools.
