///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[DATA_ACCESS009]]
=== About Heterogeneous Batch Writing

The current release provides persistence unit properties to optimize
transactions with multiple writes. The `eclipselink.jdbc.batch-writing`
property configures the use of batch writing to optimize transactions
with multiple writes. Batch writing allows multiple heterogeneous
dynamic SQL statements to be sent to the database as a single execution,
or multiple homogeneous parameterized SQL statements to be executed as a
single batch execution.Note that not all JDBC drivers, or databases
support batch writing.

The `eclipselink.jdbc.batch-writing.size` property configures the batch
size used for batch writing. For parameterized batch writing this is the
number of statements to batch, default 100. For dynamic batch writing,
this is the size of the batched SQL buffer, default 32k.

The `eclipselink.jdbc.batch-writing` persistence property can also be
used with query hints to configure if a modify query can be batched
through batch writing. Some types of queries cannot be batched, such as
DDL on some databases. Disabling batch writing will also allow the row
count to be returned.
