///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ENTITIES003]]
=== Entities and Database Tables

Every entity class maps to a specific table or set of tables in the
database. By default, the entity's table name is defaulted as its entity
name as uppercase, which defaults to the entity's short class name. An
entity normally maps to a single table, but can also map to multiple
tables, or even a view.

You can customize an entity's tables using the following annotations:

* `@Table`
* `@SecondaryTable`
