///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ENTITIES004]]
=== Entities and Inheritance

JPA defines several difference methods for persisting objects with
inheritance. The `@Inheritance` annotation is used in the root class to
define `SINGLE_TABLE, JOINED`, and `TABLE_PER_CLASS` inheritance. For
abstract classes that define common state or persistence behavior, but
have no relationship on the database, the `@MappedSuperclass` annotation
can be used.

* `@Inheritance`
* `@MappedSuperclass`
