///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

:description: EclipseLink
:keywords: eclipselink, java, jpa, persistence, expression

== Understanding EclipseLink Expressions

this chapter describes how to use the EclipseLink expressions framework
to specify query search criteria based on your domain object model.

This chapter includes the following sections:

* link:#EXPRESSION001[About the Expression Framework]
* link:#EXPRESSION002[About Expression Components]

//About the Expression Framework
include::{rootdir}/expressions001.adoc[]

//About Expression Components
include::{rootdir}/expressions002.adoc[]
