///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[NOSQL004]]
=== About Mapping NoSQL Objects

NoSQL maps objects to structured data such as XML or JSON. NoSQL
supports embedded data, embedded collections, and all of the existing
JPA mapping annotations.

To map NoSQL objects, you must define IDs, mapping, embedded objects,
relationships, and locking. For more information, see "Implementing the
Solution" in _Solutions Guide for EclipseLink_.
