///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[ADVANCEDCONCEPTS009]]
=== Customizing Generated Mappings

When bootstrapping from an XML Schema (or an EclipseLink project from
`sessions.xml`), you can customize the mappings that EclipseLink
generates by using your own EclipseLink OXM Bindings file. This file
contains your additional mappings and allows you to combine OXM with XSD
bootstrapping. This means that you can use EclipseLink mappings to
customize an existing XML schema.

This section shows how to override mappings defined in the schema.
Although the schema defines *addresses* in Canadian format (with
province and postal code), you can use XML that contains the *address*
is USA format (with state and zip code).

First, you must create an `eclipselink-oxm.xml` file that contains the
mapping overrides. In link:#CIHHDDHC[Example 8-42], we modify the XPaths
for `province` and `postalCode`:

[[CIHHDDHC]]

*_Example 8-42 Sample eclipselink-oxm.xml File_*

[source,oac_no_warn]
----
<?xml version="1.0" encoding="US-ASCII"?>
<xml-bindings xmlns="http://www.eclipse.org/eclipselink/xsds/persistence/oxm" package-name="example">
      <java-types>
        <java-type name="Address">
            <java-attributes>
                <xml-element java-attribute="province" xml-path="state/text()"/>
                <xml-element java-attribute="postalCode" xml-path="zip-code/text()"/>
            </java-attributes>
        </java-type>
    </java-types>
</xml-bindings>
 
----

When you create a `DynamicJAXBContext`, use the properties argument to
pass this binding file to the `DynamicJAXBContextFactory` (in addition
to the Schema):

[source,oac_no_warn]
----
 
// Load Schema
InputStream xsdStream = myClassLoader.getSystemResourceAsStream("example/resources/xsd/customer.xsd");
 
// Load OXM with customizations, put into Properties
InputStream oxmStream = myClassLoader.getSystemResourceAsStream("example/resources/eclipselink/eclipselink-oxm.xml");
Map<String, Object> props = new HashMap<String, Object>();
props.put(JAXBContextProperties.OXM_METADATA_SOURCE, oxmStream);
 
// Create Context
DynamicJAXBContext dContext = DynamicJAXBContextFactory.createContextFromXSD(inputStream, null, myClassLoader, props);
----
