///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[DYNAMICJAXB]]
== Using Dynamic JAXB

This chapter includes the following sections:

* xref:{relativedir}/dynamic_jaxb001.adoc#DYNAMICJAXB001[Understanding Static and Dynamic Entities]
* xref:{relativedir}/dynamic_jaxb002.adoc#DYNAMICJAXB002[Specifying the EclipseLink Runtime]
* xref:{relativedir}/dynamic_jaxb003.adoc#DYNAMICJAXB003[Bootstrapping from XML Schema (XSD)]
* xref:{relativedir}/dynamic_jaxb004.adoc#DYNAMICJAXB004[Bootstrapping from EclipseLink Metadata (OXM)]

//Understanding Static and Dynamic Entities
include::{rootdir}/dynamic_jaxb001.adoc[]

//Specifying the EclipseLink Runtime
include::{rootdir}/dynamic_jaxb002.adoc[]

//Bootstrapping from XML Schema (XSD)
include::{rootdir}/dynamic_jaxb003.adoc[]

//Bootstrapping from EclipseLink Metadata (OXM)
include::{rootdir}/dynamic_jaxb004.adoc[]
