///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[JAXBJSON]]
== Using JSON Documents

Starting in Release 2.4, EclipseLink MOXy supports the ability to
convert objects to and from JSON (JavaScript Object Notation). This
feature is useful when creating RESTful services; JAX-RS services can
accept both XML and JSON messages.

This chapter includes the following sections:

* xref:{relativedir}/json001.adoc#JAXBJSON001[Understanding JSON Documents]
* xref:{relativedir}/json002.adoc#JAXBJSON002[Marshalling and Unmarshalling JSON Documents]
* xref:{relativedir}/json003.adoc#JAXBJSON003[Specifying JSON Bindings]

//Understanding JSON Documents
include::{rootdir}/json001.adoc[]

//Marshalling and Unmarshalling JSON Documents
include::{rootdir}/json002.adoc[]

//Specifying JSON Bindings
include::{rootdir}/json003.adoc[]