///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[SIMPLEVALUES]]
== Mapping Simple Values

This chapter includes the following sections:

* xref:{relativedir}/simple_values001.adoc#SIMPLEVALUES001[Mapping Simple Values]
* xref:{relativedir}/simple_values002.adoc#SIMPLEVALUES002[Mapping Collections of Simple Values]
* xref:{relativedir}/simple_values003.adoc#SIMPLEVALUES003[Multiple Mappings for a Single Property]
* xref:{relativedir}/simple_values004.adoc#SIMPLEVALUES004[Mapping Enums]

//Mapping Simple Values
include::{rootdir}/simple_values001.adoc[]

//Mapping Collections of Simple Values
include::{rootdir}/simple_values002.adoc[]

//Multiple Mappings for a Single Property
include::{rootdir}/simple_values003.adoc[]

//Mapping Enums
include::{rootdir}/simple_values004.adoc[]
