///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[SPECIALSCHEMATYPES]]
== Mapping Special Schema Types

This chapter includes the following sections:

* xref:{relativedir}/special_schema_types001.adoc#SPECIALSCHEMATYPES001[Mapping Dates and Times]
* xref:{relativedir}/special_schema_types002.adoc#SPECIALSCHEMATYPES002[Mapping to a Union Field]
* xref:{relativedir}/special_schema_types003.adoc#SPECIALSCHEMATYPES003[Binary Types]

//Mapping Dates and Times
include::{rootdir}/special_schema_types001.adoc[]

//Mapping to a Union Field
include::{rootdir}/special_schema_types002.adoc[]

//Binary Types
include::{rootdir}/special_schema_types003.adoc[]
