///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[TYPELEVEL]]
== Mapping Type Levels

This chapter includes the following sections:

* xref:{relativedir}/type_level001.adoc#TYPELEVEL001[Defining the Default Root Element]
* xref:{relativedir}/type_level002.adoc#TYPELEVEL002[Setting Up Namespace Information]
* xref:{relativedir}/type_level003.adoc#TYPELEVEL003[Specifying Inheritance]

//Defining the Default Root Element
include::{rootdir}/type_level001.adoc[]

//Setting Up Namespace Information
include::{rootdir}/type_level002.adoc[]

//Specifying Inheritance
include::{rootdir}/type_level003.adoc[]
