///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2024 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

== Examples

The following examples are provided to assist developers with their adoption
and usage of EclipseLink's SDO functionality.

* Getting started
** <<sdo-example-basic>>
** <<sdo-example-metadata>>
// ** Customizing your XSD for SDO Usage
* Using Dynamic Data Objects
** <<sdo-example-dynamicapi>>
** <<sdo-example-dynamicapixml>>
* Using Static Data Objects
** <<sdo-example-compiler>>
** <<sdo-example-static>>
* Data Access Service - These examples focus on the usage of SDO with alternative value stores.
** <<sdo-example-xmlbinding>>
** <<sdo-example-persistence>>

// Getting Started
include::BasicAPI.adoc[]

include::MetadataXMLSchema.adoc[]

// Using Dynamic Data Objects
include::DynamicAPI.adoc[]

include::DynamicAPIXML.adoc[]

// Using Static Data Objects
include::Compiler.adoc[]

include::StaticAPI.adoc[]

// Data Access Service
include::JAXB.adoc[]

include::JPA.adoc[]

