///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

= Developing Persistence Architectures Using EclipseLink Database Web Services
:nofooter:
:description: EclipseLink
:keywords: eclipselink, java, jpa, persistence, dbws, web service
:commondir: ../../../../common
include::{commondir}/attributes.adoc[]

//Title and Copyright Information
include::{rootdir}/title_eclipselink.adoc[]

//Preface
[preface]
include::{rootdir}/preface.adoc[]

//List of Examples
:sectnums!:
include::{rootdir}/loe.adoc[]

//Overview of EclipseLink
:sectnums:
:sectnumlevels: 1
include::{rootdir}/overview.adoc[]

//Creating DBWS Services
include::{rootdir}/creating_dbws_services.adoc[]

//Advanced Methods of Accessing DBWS Designtime API
include::{rootdir}/advanced_methods.adoc[]

include::{commondir}/copyright.adoc[]
