///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[RUNTIME001]]
=== Specifying the EclipseLink Runtime

To use EclipseLink MOXy as your JAXB implementation, identify the
EclipseLink `JAXBContextFactory` in your `jaxb.properties` file.

. Create a text file named `jaxb.properties`, specifying EclipseLink's
`JAXBContextFactory` as the factory used to build new `JAXBContexts`:
+
[source,oac_no_warn]
----
jakarta.xml.bind.context.factory=org.eclipse.persistence.jaxb.JAXBContextFactory
----
. Copy the file to the same package (directory) in which your model
classes reside.
. Use the standard `JAXBContext.newInstance(Class... classesToBeBound)`
API to create a JAXBContext:
+
[source,oac_no_warn]
----
JAXBContext jaxbContext = JAXBContext.newInstance(Customer.class);
----

Because you do not need to change any application code, you can easily
switch between different JAXB implementations.

For more information on different ways to create a `JAXBContext`, see
xref:{relativedir}/runtime002.adoc#RUNTIME002["Bootstrapping"].
