///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////

== EclipseLink

Developing JAXB Applications Using EclipseLink MOXy {release-version}

{release-date}
*Developing JAXB Applications Using EclipseLink MOXy {release-version}

Copyright © 2013 by The Eclipse Foundation under the Eclipse Public
License (EPL).

`http://www.eclipse.org/org/documents/epl-v10.php`

The initial contribution of this content was based on work copyrighted
by Oracle and was submitted with permission.

Print date: {print-date}
