///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[RESTJPA003]]
=== Additional Resources

See the following resources for more information about the technologies
and tools used to implement the solutions in this chapter:

* "Building RESTful Web Services with JAX-RS" in The Jakarta EE 6
Tutorial at `http://docs.oracle.com/javaee/6/tutorial/doc/giepu.html`.
* "RESTful Service Example" at
`http://wiki.eclipse.org/EclipseLink/Examples/REST/GettingStarted`.
* JSR 311: JAX-RS: The Java API for RESTful Web Services" at
`http://jcp.org/en/jsr/detail?id=311`
* Jersey project at `http://jersey.java.net/`.
