///////////////////////////////////////////////////////////////////////////////

    Copyright (c) 2022 Oracle and/or its affiliates. All rights reserved.

    This program and the accompanying materials are made available under the
    terms of the Eclipse Public License v. 2.0, which is available at
    http://www.eclipse.org/legal/epl-2.0.

    This Source Code may also be made available under the following Secondary
    Licenses when the conditions for such availability set forth in the
    Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
    version 2 with the GNU Classpath Exception, which is available at
    https://www.gnu.org/software/classpath/license.html.

    SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0

///////////////////////////////////////////////////////////////////////////////
[[RESTJPA001]]
=== Introduction to the Solution

REpresentational State Transfer (REST) defines a set of architectural
principles for distributed systems, in which Web Services are viewed as
resources. Those resources are identified by URIs and can be addressed
and transferred using the HTTP protocol. REST can be used with a number
of technologies, including JPA. HTTP methods are used to access and
perform operations on resources.

The Java API for RESTful Web Services (JAX-RS) is an API designed to
make it easy to develop Java applications that use the REST
architecture. With JAX-RS, you use annotations to define resources and
the actions that can be performed on those resources.

While it is possible to use JAX-RS directly to interact with JPA
persistence units in a RESTful application, RESTful Data Services
provide an API that makes it easier to implement REST for JPA
persistence,. You can use this API to interact with JPA persistence
units without explicitly writing JAX-RS code, thus providing a simple
way to expose persistence units through REST.

NOTE: For an example that uses JAX-RS directly to implement JPA persistence in
a RESTful application, see "RESTful Service Example" at
`http://wiki.eclipse.org/EclipseLink/Examples/REST/GettingStarted`. For
information about simplifying that process by using RESTful Data
Services, continue reading this chapter.

RESTful Data Services are made available via a web fragment, which
extends the capabilities of a web application. The REST functionality is
made available by including the RESTful Data Services JAR file in the
`WEB-INF/lib` folder of a web application.

The RESTful Data Services runtime provides access to all persistence
units packaged in the application in which it is running, as well as any
dynamic persistence units that are provisioned within it.
