#!/usr/bin/env bash
#
# Copyright (c) 2019 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

echo "#####DISTRIBUTION module cleanup - begin#####"

. ./distribution_environment.sh

#Cleanup directories generated by commons_prepare.sh script
rm -rfv ${BUNDLES_DISTRIBUTION_DIR}/src/main/scripts
rm -rfv ${BUNDLES_DISTRIBUTION_DIR}/src/test
rm -rfv ${BUNDLES_OTHERS_DIR}/src/main/resources/nonfiltered/eclipselink-test-src.zip

echo "#####DISTRIBUTION module cleanup - end#####"
