#!/usr/bin/env bash
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

echo "#####Oracle Spatial Extension module cleanup - begin#####"

. ./extension_oracle_spatial_environment.sh

#Cleanup directories generated by extension_oracle_spatial_prepare.sh script
rm -rfv ${EXTENSION_ORACLE_SPATIAL_DIR}/src

echo "#####Oracle Spatial Extension module cleanup - end#####"
