#!/usr/bin/env bash
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

echo "#####JPA JPA-RS module cleanup - begin#####"

. ./jpa_jpars_environment.sh

#Cleanup directories generated by jpa_jpars_prepare.sh script
rm -rfv ${JPA_JPARS_DIR}/src

echo "#####JPA JPA-RS module cleanup - end#####"
