#!/usr/bin/env bash
#
# Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0,
# or the Eclipse Distribution License v. 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: EPL-2.0 OR BSD-3-Clause
#

echo "#####DBWS BUILDER module cleanup - begin#####"

. ./utils_dbws_builder_environment.sh

#Cleanup directories generated by utils_dbws_builder_prepare.sh script
rm -rfv ${DBWS_BUILDER_DIR}/src

#Cleanup DBWS Builder Oracle Test
rm -rfv ${DBWS_BUILDER_TEST_ORACLE}/src

#Cleanup DBWS Builder Oracle Server Test
rm -rfv ${DBWS_BUILDER_TEST_ORACLE_SERVER}/src

echo "#####DBWS BUILDER module cleanup - end#####"
